### ISSUE TITLE
Frontend things 

### ISSUE THREAD

**Issue by mashuDuek** [AnJuHyppolite/budgeting-app-frontend#1]
Hey AnJu! This is looking 🔥 
Couple things: 
1. When I navigate to any of the other routes, and refresh it break with some Netlify 404 page. Please check the bottom of [this](https://github.com/joinpursuit/budgeting-app-project-prompt/blob/main/netlify-cra.md) page (the redirects things) to fix this. 
2. When I add a new transaction the total goes crazy. Remember we saw this was a Num vs Str issue. 
3. Add a little styling to the list of transactions please :). Make it more table-like, rather than simple `<li>`'s

**Comment by AnJuHyppolite** [comment]
Done. Thank you, Mashu.
