### ISSUE TITLE
Current Frontend Issues

### ISSUE THREAD

**Issue by gigimscarborough** [AnJuHyppolite/budgeting-app-frontend#2]
- [x] Your front end appears to be a nested repo. You shouldn’t have more than one package.json here.
- [x] Have you forgotten to push your front end code? I only see 2 components here.
- [x] I can’t see your css files to verify that you have responsive styling on each page and your index does not appear to be responsive.
- [x] You application breaks on a refresh. Let’s talk if you not sure why thats happening or how to fix it (it is the netlify redirect issue).
- [x] I can see that you used react-router-dom from the console but I can’t be sure you made your api calls with axios unless I have access to your front end code.

**Comment by AnJuHyppolite** [comment]
The styling has been updated. Thank you, Gigi.
